import 'package:donut_game/modes/bad_batch/bb_cards.dart';

/// The deck that ships with the game, so Bad Batch works offline and without
/// any imports. Adults only. Each "_" is a blank.
final Deck builtinDeck = Deck(
  code: 'builtin',
  name: 'The Day-Old Dozen (built in)',
  prompts: _prompts.map(PromptCard.parse).toList(),
  responses: _responses.map(ResponseCard.new).toList(),
);

const _prompts = [
  'What ruined the office holiday party?_',
  'My therapist says I need to stop relying on _.',
  'The secret ingredient in our glazed donuts is _.',
  'What did I find in my search history this morning?_',
  'I never truly understood love until I experienced _.',
  'Coming soon to a strip mall near you: _.',
  'What got me banned from the family group chat?_',
  'In lieu of flowers, the family requests _.',
  'The doctor took one look and said, "That\'s definitely _."',
  'What\'s that smell?_',
  'My last relationship ended because of _.',
  'Hot new wellness trend: _.',
  'What\'s the real reason the donut has a hole?_',
  'Instead of a gender reveal, we\'re doing a _ reveal.',
  'The 3 a.m. drive-thru only serves _.',
  'Grandma\'s final words were: "Never forget _."',
  'What\'s my safe word?_',
  'Step one: _. Step two: _. Step three: profit.',
  'I\'m not proud of it, but I paid good money for _.',
  'Tonight on the nature channel: _ in its natural habitat.',
  'What did the bachelor party end with?_',
  'The worst thing to hear during a colonoscopy: "Is that _?"',
  'My TED talk is just 18 minutes of _.',
  'What\'s hidden in the walk-in freezer?_',
  'New flavour at the donut shop: _ with sprinkles.',
  'Nothing says "I\'m sorry" like _.',
  'The HR complaint simply read: _.',
  '_ is how I want to die.',
  'Honey, I think we need to talk about _.',
  'What got me kicked out of the hot tub?_',
  'The church bake sale is going to be awkward after _.',
  'My dating profile: "Looking for someone who can handle _."',
  'What\'s in the mystery jelly?_',
  'They found me passed out next to _.',
  'Breaking news: local man arrested for _.',
  '_ + _ = a very long weekend.',
  'What finally broke the bartender?_',
  'Parenting tip: when all else fails, try _.',
  'My spirit animal is _.',
  'I\'d sell my soul for _.',
  'What did Santa leave in my stocking this year?_',
  'Rejected donut shop slogan: "Now with 40% more _!"',
  'The cops showed up because of _.',
  'Doctors hate this one weird trick: _.',
  'What\'s the most romantic thing you can do with a cruller?_',
  'In my defence, _ was very consensual.',
  'I knew it was time to leave the cult when _ showed up.',
  'Just once, I\'d like to wake up without _.',
  'My mom found _ in my laundry.',
  'The only thing worse than a donut is _.',
];

const _responses = [
  'A raw, unprotected cruller.',
  'Licking the frosting off a stranger.',
  'My ex\'s new, better-looking partner.',
  'A tactical amount of lube.',
  'Getting sexually aroused by a bear claw.',
  'Crying in the walk-in fridge.',
  'An unsupervised colonoscopy.',
  'Explosive diarrhoea at a funeral.',
  'Grandpa\'s secret porn stash.',
  'A sad little handjob.',
  'Faking my own death to avoid brunch.',
  'Drunk-texting my dentist.',
  'A suspicious lump.',
  'The glory hole behind the donut shop.',
  'Whatever is growing in the deep fryer.',
  'Doing coke off a toilet seat.',
  'Morning wood at a job interview.',
  'An emotional support ferret with rabies.',
  'Shotgunning a beer in the delivery room.',
  'A threesome with regret and a bad decision.',
  'Hiding a body in the dumpster out back.',
  'Pissing myself with excitement.',
  'Tasting my own feet.',
  'A crotch-mounted donut holder.',
  'The sweet release of death.',
  'Sexting with typos.',
  'Mom\'s new boyfriend, Chad.',
  'A full-body wax gone horribly wrong.',
  'Huffing powdered sugar.',
  'A buttplug shaped like a Boston creme.',
  'Being haunted by my own nudes.',
  'Losing my virginity to the theme from Titanic.',
  'A dad bod and a dream.',
  'Overdosing on sprinkles.',
  'Quietly sharting during yoga.',
  'Getting railed by the tax man.',
  'An open casket and an open bar.',
  'Spooning a stranger at a bus stop.',
  'My browser history, read aloud at my wedding.',
  'Moist, warm dough.',
  'Being a strong, independent alcoholic.',
  'A tiny, tiny penis.',
  'Absolutely massive tits.',
  'Fifty-year-old swingers.',
  'Shame-eating a dozen donuts in the car.',
  'A hot tub full of strangers\' bodily fluids.',
  'Getting a lap dance from a tax auditor.',
  'Dying alone and being eaten by my cats.',
  'A haunted dildo.',
  'Stepping on a used condom barefoot.',
  'Blacking out at a children\'s birthday party.',
  'Getting caught masturbating by a Roomba.',
  'A sudden, intense urge to shit.',
  'Two old people having loud sex.',
  'My uncle\'s unlicensed tattoo parlour.',
  'Lying about being a doctor to get laid.',
  'The bucket of grease out back.',
  'Body glitter in places it should never be.',
  'A clown at a funeral.',
  'Snorting a line of powdered sugar off a cop.',
  'Divorce.',
  'A prenup written on a napkin.',
  'Inappropriate eye contact during sex.',
  'A therapist who takes notes and laughs.',
  'Erectile dysfunction.',
  'My last brain cell.',
  'Ketamine and karaoke.',
  'A tasteful nude in the company newsletter.',
  'A fart so loud it set off a car alarm.',
  'Vomiting into my own purse.',
  'My mother-in-law\'s thong.',
  'Being sacrificed to a dark god.',
  'A mid-life crisis Lamborghini.',
  'Kissing my cousin "just to practise".',
  'An ill-advised Brazilian wax.',
  'Pretending to care.',
  'The smell of burnt hair and regret.',
  'Sweaty middle-aged men in a sauna.',
  'Edible underwear made of bacon.',
  'Taking a dump in a wedding dress.',
  'The intern\'s OnlyFans.',
  'An extremely aggressive foot fetish.',
  'Waking up in a ditch with no pants.',
  'Ghosting someone at the altar.',
  'A family reunion that turns into an orgy.',
  'Licking a battery for the thrill.',
  'Being too drunk to find my own face.',
  'Mild public indecency.',
  'A cursed sex toy from an estate sale.',
  'Getting high with the minister.',
  'Pooping in the shower and stepping on it.',
  'A sloppy, wet kiss from a basset hound.',
  'Using the dog as a wingman.',
  'The cast of a low-budget porno.',
  'Self-loathing with sprinkles on top.',
  'Hiding vodka in a holy water bottle.',
  'Slowly realising I\'m the villain.',
  'Hungover at a christening.',
  'A man bun and no personality.',
  'Asking for a friend.',
  'Eating ass for the first time.',
  'A colonoscopy video on the jumbotron.',
  'Being so horny I can see sounds.',
  'Getting high off the fumes of a deep fryer.',
  'A strap-on and a dream.',
  'Peeing in the pool and owning it.',
  'Selling my organs for rent money.',
  'A furry convention in the next hotel room.',
  'Accidentally sexting my priest.',
  'Two days of unwashed balls.',
  'A body that\'s 60% gravy.',
  'Making eye contact with myself during sex.',
  'A coffin full of donuts.',
  'Dirty talk in a baby voice.',
  'Getting my nipple pierced at a gas station.',
  'Flashing the security camera.',
  'Telling the kids where babies really come from.',
  'The ghost of a dead pornstar.',
  'An enema gone rogue.',
  'Grinding on a mall Santa.',
  'Being the last person anyone would call.',
  'The forbidden glaze.',
  'Trying to seduce a home inspector.',
  'Throwing up on the first date and then marrying them.',
  'Losing a finger in the donut machine.',
  'A naked man running through the drive-thru.',
  'Tequila for breakfast.',
  'An urn full of Grandpa and glitter.',
  'Sharting at the gym.',
  'Moaning loudly while eating a donut in public.',
  'A one-night stand with a sentient sourdough starter.',
  'Using a dildo as a doorstop.',
  'A shame-fuelled 3 a.m. donut run.',
  'Calling out the wrong name during sex.',
  'The sex dungeon in the basement.',
  'An erotic fan fiction about the cops.',
  'Death by chocolate. Literally.',
  'Snorting a Pixy Stix and feeling invincible.',
  'Getting dumped by text, in emojis.',
  'Ruining Thanksgiving with the truth.',
  'Sitting on a whoopee cushion during a eulogy.',
  'The orgasm face of a disappointed father.',
  'A sweaty, unwanted hug.',
  'Mouth-to-mouth from a drunk lifeguard.',
  'Licking the security glass at the bakery.',
  'Finding out the kids aren\'t mine.',
  'Spontaneous combustion during foreplay.',
  'A box of day-old regrets.',
  'Being married to my work. And my work wants a divorce.',
  'Having a threesome with the Holy Trinity.',
  'Bleaching my asshole.',
  'Sneezing mid-thrust.',
];
