import 'package:donut_game/modes/bad_batch/bb_cards.dart';

/// The X-rated pack: explicit sex and kink between consenting adults, gross-out
/// and dark humour. Off by default; switch it on in the deck options. Each "_" is a blank.
final Deck creamFilledDeck = Deck(
  code: 'builtin-x',
  name: 'Cream-Filled (built in, X-rated)',
  prompts: _prompts.map(PromptCard.parse).toList(),
  responses: _responses.map(ResponseCard.new).toList(),
);

const _prompts = [
  'What\'s the secret to a truly cream-filled experience?_',
  'My OnlyFans finally took off when I started doing _.',
  'Pornhub\'s new top category: _.',
  'What did the hotel maid find under the bed?_',
  'Nothing kills the mood faster than _.',
  'My kink? Honestly, it\'s _.',
  'The sex shop clerk didn\'t even blink at _.',
  'What\'s the worst thing to moan by accident?_',
  'Foreplay is just _ with extra steps.',
  'Tinder bio: "Swipe right if you\'re into _."',
  'We had to stop the threesome because of _.',
  'My partner\'s browser history is 90% _.',
  'The couples\' therapist recommended _.',
  'What\'s in the drawer of the bedside table?_',
  '_: the reason I\'m banned from the swingers\' club.',
  'Fifty Shades of _.',
  'I lost my virginity to _ and _.',
  'Rejected sex toy name: "The _."',
  'My most expensive mistake on a cam site: _.',
  'What\'s the dirtiest thing you can do with a jelly donut?_',
  'Tonight\'s erotic fan fiction pairs _ with _.',
  'What\'s that sticky stain on the couch?_',
  'Day one of the honeymoon: _. Day two: _.',
  'The new position from the Kama Sutra: _.',
  'What made the dominatrix ask for a raise?_',
  'I came. I saw. I _.',
  'Turns out the walls are thin enough to hear _.',
  'Not tonight, honey, I\'ve got _.',
  'What really happened in the champagne room?_',
  'My safe word used to be "pineapple". Now it\'s _.',
  'Every porno starts with _ and ends with _.',
  'Best way to fake an orgasm: _.',
  'What\'s the real reason the donut has a hole?_',
  'Spicy new item on the drive-thru menu: _.',
  'The adult film was called "Glazed and Confused" and featured _.',
  'What does the morning-after text say?_',
  'Grindr has a filter for _ now.',
  'My sexual awakening was _.',
  'The marriage survived the affair but not _.',
  'Bachelorette party favours this year: _.',
  'What got the strip club a bad Yelp review?_',
  'I swiped left on _ but right on _.',
  'The sex ed teacher\'s TED talk: "_."',
  'I\'m into _, but only on weekends.',
  'What\'s hidden behind the curtain at the back of the donut shop?_',
  'Tonight\'s date ended with _.',
  'Ladies and gentlemen, the new Love Island twist: _.',
  'The kinkiest thing at the office Secret Santa: _.',
  'Doctor, it hurts when I do _.',
  'Phone sex got awkward when I mentioned _.',
  'What\'s leaking out of the dungeon\'s front door?_',
  'The safe word didn\'t work because of _.',
  'My dom\'s aftercare routine involves _.',
  'What\'s in the jar labelled "DO NOT EAT" in the break room?_',
  'The coroner listed the cause of death as _.',
  'My will leaves everything to _.',
  'What\'s the weirdest thing you can find at a fetish convention?_',
  'Golden showers are out. This year it\'s all about _.',
  'Eulogy, in full: "He loved _."',
  'The health inspector shut us down after finding _ in the fryer.',
  'I\'d rather die than _. Actually, scratch that: _.',
  'What\'s that smell coming from the sex dungeon?_',
  'Sign you\'ve hit rock bottom: _.',
  'The BDSM contract has a clause about _.',
  'Funeral home upsell: _.',
  'What\'s dripping from the ceiling of the porta-potty?_',
];

const _responses = [
  'A cream-filled surprise.',
  'Getting glazed.',
  'Two hands and a dream.',
  'Deepthroating a cruller.',
  'A strap-on named Gary.',
  'Edging for six hours straight.',
  'Morning wood.',
  'A really sloppy blowjob.',
  'A crotch-mounted donut holder.',
  'Accidentally sexting my boss.',
  'Butt plugs at airport security.',
  'Pegging the pastor.',
  'Spit-roasting at the company retreat.',
  'Sixty-nining in a hot tub.',
  'Premature ejaculation.',
  'The walk of shame in last night\'s heels.',
  'A dildo shaped like a maple bar.',
  'Queefing during yoga.',
  'Tossed salad with extra dressing.',
  'A tactical amount of lube.',
  'Choking on a ball gag.',
  'An extremely aggressive foot fetish.',
  'Swallowing.',
  'Spitting.',
  'Getting caught masturbating by a Roomba.',
  'A sad little handjob.',
  'Furries going at it in full costume.',
  'Hairy, sweaty man-cleavage.',
  'Nipple clamps on Christmas morning.',
  'Sexy Pikachu cosplay.',
  'A Fleshlight full of frosting.',
  'The reverse cowgirl.',
  'The reverse reverse cowgirl.',
  'Scissoring.',
  'An all-night orgy at the Costco.',
  'Licking glaze off a stranger\'s nipples.',
  'An enthusiastic rim job.',
  'Phone sex with my accountant.',
  'A dick pic with terrible lighting.',
  'Unsolicited dick pics.',
  'Ben Wa balls at a job interview.',
  'Glory hole etiquette.',
  'Too much tongue.',
  'Not enough tongue.',
  'A pearl necklace.',
  'Spanking it to the shopping channel.',
  'Bondage with Christmas lights.',
  'Fisting.',
  'A vibrator with Bluetooth and no password.',
  'Daddy issues.',
  'Mommy issues.',
  'Tantric breathing exercises.',
  'Cumming in thirty seconds flat.',
  'A wet T-shirt contest at the nursing home bingo night.',
  'The missionary position, but angry.',
  'Squirting on the new sofa.',
  'An awkward erection in a job interview.',
  'Blue balls.',
  'Shower sex that ended in an ER visit.',
  'A chastity cage with a lost key.',
  'Swingers with a timeshare.',
  'Lap dances from a guy named Kevin.',
  'A sloppy second.',
  'Crotchless panties.',
  'A latex bodysuit in July.',
  'Feet pics for crypto.',
  'Leather chaps and nothing else.',
  'A threesome where two people fell asleep.',
  'Teabagging.',
  'Motorboating.',
  'Camel toe.',
  'Moose knuckle.',
  'A cock ring stuck at the worst possible time.',
  'Dirty talk read off index cards.',
  'Moaning my ex\'s name.',
  'Faking it.',
  'Breast milk in the coffee.',
  'Banging in the walk-in freezer.',
  'Doing it in the drive-thru.',
  'A happy ending.',
  'Erotic asphyxiation done wrong.',
  'Sexting with autocorrect on.',
  'A full-body frosting massage.',
  'Getting railed.',
  'Getting absolutely pounded.',
  'Dry humping in the church parking lot.',
  'A really big, juicy éclair.',
  'Strap-on Sunday.',
  'Kegel exercises during a board meeting.',
  'Sending nudes to the family group chat.',
  'Rug burn in places rugs shouldn\'t reach.',
  'Wearing my partner\'s underwear.',
  'A gimp suit.',
  'Joining the mile-high club.',
  'Joining the mile-high club, alone.',
  'Sex on a waterbed with a leak.',
  'A body shot off a bodybuilder.',
  'Role-playing as the IRS.',
  'Role-playing as the pizza guy.',
  'Getting tied up and forgotten.',
  'A rubber fist.',
  'Edible underwear past its expiry date.',
  'Making a sex tape on a flip phone.',
  'Hentai.',
  'A thirst trap.',
  'A cuckold with a clipboard.',
  'Dominating a man in a business suit.',
  'Calling him "sir".',
  'Calling her "ma\'am".',
  'Calling them "the boss".',
  'Bedroom eyes.',
  'A wet dream about the Pope.',
  'Accidentally sitting on a vibrator.',
  'An inflatable sex doll with a slow leak.',
  'Using the good towels afterwards.',
  'The sex swing that came down from the ceiling.',
  'A suspiciously moist donut.',
  'Lube made of maple syrup.',
  'Crying during sex.',
  'Laughing during sex.',
  'Sex with the lights on.',
  'A booty call at 4 a.m.',
  'Getting a boner during the anthem.',
  'Slow, sensual tongue kissing.',
  'An OnlyFans for my elbows.',
  'Panting like a golden retriever.',
  'Accidentally livestreaming it.',
  'A strip tease set to the Jeopardy theme.',
  'Giving head in a parked Prius.',
  'Pubes in the frosting.',
  'Manscaping with a lawn trimmer.',
  'A Brazilian wax gone horribly wrong.',
  'An orgasm so loud the neighbours called 911.',
  'Covering my whole body in sprinkles.',
  'Licking the whipped cream off.',
  'A cream pie.',
  'A Boston Creme, if you know what I mean.',
  'Bareback in a beanbag chair.',
  'A sexy librarian.',
  'A sexy plumber with no butt crack shame.',
  'Thigh-high stockings.',
  'Sexy, sexy accounting.',
  'Bending over for a glazed twist.',
  'A tongue piercing.',
  'Getting freaky at the farmers\' market.',
  'A dirty weekend in Wichita.',
  'Hooking up at a funeral.',
  'Oral sex with a mouthful of Pop Rocks.',
  'Being somebody\'s dirty little secret.',
  'Spooning that turned into forking.',
  'Ass.',
  'Titties.',
  'A golden shower.',
  'A brown shower, sadly.',
  'Felching.',
  'Snowballing.',
  'A twelve-inch double-ended dildo.',
  'Cock and ball torture.',
  'Hot wax on the taint.',
  'Electro-stimulation with a car battery.',
  'A full human pony play setup.',
  'Being walked on a leash through Walmart.',
  'Rope bondage by a Boy Scout dropout.',
  'Forty-eight hours in a sensory deprivation hood.',
  'A sounding rod.',
  'Pissing in a lover\'s mouth.',
  'Smelly feet in fishnets.',
  'A human toilet fetish.',
  'Stepping on balls in stilettos.',
  'Lactation play.',
  'A diaper fetish.',
  'Cumming in a donut and serving it to the boss.',
  'Explosive diarrhoea on the first date.',
  'Projectile vomiting into a mosh pit.',
  'A used tampon in the salad bar.',
  'Toenail clippings in the soup.',
  'Earwax candles.',
  'A pimple that won\'t stop squirting.',
  'A loaf of pubes.',
  'Ass sweat on a leather car seat.',
  'Shitting my pants at a job interview.',
  'Smegma.',
  'A crusty sock under the bed.',
  'Licking a public toilet seat on a dare.',
  'An abscess that pops at the dinner table.',
  'Sharting in a wedding dress.',
  'Period sex on white sheets.',
  'Drinking bathwater sold on the internet.',
  'Grandpa\'s open casket selfie.',
  'Being cremated with my vibrator.',
  'Dying alone, surrounded by cats who are already eating me.',
  'Outliving all my enemies and then being very bored.',
  'A midlife crisis Lamborghini wrapped around a tree.',
  'My liver filing for divorce.',
  'Embalming fluid with a lime wedge.',
  'Selling my kidney for concert tickets.',
  'A Viking funeral in a kiddie pool.',
  'Leaving my body to science, and science returning it.',
  'Becoming a ghost and haunting the Arby\'s.',
  'A hospice volunteer who\'s in it for the inheritance.',
  'Crippling, bottomless debt.',
  'My therapist quitting therapy.',
  'Sobbing into a family-size bag of Doritos.',
  'The crushing realisation that this is it.',
  'Waking up in a stranger\'s bathtub with one less kidney.',
  'Getting dumped at my own birthday party.',
  'Writing my own obituary in Comic Sans.',
  'Being the only person at my own funeral.',
  'Stepping on a Lego and seeing God.',
  'Cannibalism, but only on weekends.',
  'Eating the evidence.',
  'Burying a body under the donut shop.',
];
